apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
  annotations:
    link.argocd.argoproj.io/external-link: https://otbeaumont.me
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
