apiVersion: v1
kind: Namespace
metadata:
  name: k8s-argo-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
